version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "14:ea:eb:53:f6:b0:7b:e6:83:8b:e2:c8:ba:ea:8e:e4"
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: pwd
          command: echo $PWD
      - run:
          name: ls
          command: echo $LS