version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "14:ea:eb:53:f6:b0:7b:e6:83:8b:e2:c8:ba:ea:8e:e4"
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: build project
          command: yarn build
      - run:
          name: deploy to gh pages
          command: |
            git config user.email "wotzhs@gmail.com"
            git config user.name "circleci-deployment"
            mv build ../
            rm -rf *
            mv ../build/* .
            git add .
            LAST_COMMIT=$(git log --oneline -1 | awk '{print $1}')
            git checkout gh-pages
            git add .
            git commit -m "deploy ${LAST_COMMIT}"
            git push --force